# Generated by Django 5.2 on 2025-09-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update Time')),
                ('user', models.ForeignKey(help_text='Owner of the itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'db_table': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(verbose_name='Day Number')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Summary')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update Time')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='itinerary.itinerary', verbose_name='Itinerary')),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'db_table': 'daily_schedules',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('target_audience', models.CharField(blank=True, max_length=255, verbose_name='Target Audience')),
                ('booking_link', models.CharField(blank=True, max_length=500, verbose_name='Booking Link')),
                ('avg_duration', models.IntegerField(blank=True, null=True, verbose_name='Average Duration (minutes)')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='Opening Hours')),
                ('ticket_price', models.CharField(blank=True, max_length=100, verbose_name='Ticket Price')),
                ('review_summary', models.TextField(blank=True, verbose_name='Review Summary')),
                ('review_source', models.CharField(blank=True, max_length=255, verbose_name='Review Source')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update Time')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='itinerary.dailyschedule', verbose_name='Daily Schedule')),
            ],
            options={
                'verbose_name': 'POI',
                'verbose_name_plural': 'POIs',
                'db_table': 'poi',
            },
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['user'], name='itineraries_user_id_84a30a_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['create_time'], name='itineraries_create__208938_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['update_time'], name='itineraries_update__c5d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['itinerary'], name='daily_sched_itinera_68d436_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['day_number'], name='daily_sched_day_num_02b580_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['create_time'], name='daily_sched_create__00597e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['update_time'], name='daily_sched_update__b8d17e_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['name'], name='poi_name_247537_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['category'], name='poi_categor_3564fa_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['create_time'], name='poi_create__53fca0_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['update_time'], name='poi_update__20771b_idx'),
        ),
    ]
