# Generated by Django 5.2.6 on 2025-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="destination",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Destination"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duration (days)"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="isCompleted",
            field=models.CharField(
                choices=[("Generated", "Generated"), ("Completed", "Completed")],
                default="Generated",
                max_length=20,
                verbose_name="Completion Status",
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="llm_response",
            field=models.JSONField(
                blank=True,
                help_text="Complete LLM response for quick display",
                null=True,
                verbose_name="LLM Generated Plan",
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start Time"
            ),
        ),
    ]
