# Generated by Django 5.2.6 on 2025-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0002_itinerary_destination_itinerary_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="isCompleted",
            field=models.CharField(
                choices=[
                    ("Temporary", "Temporary"),
                    ("Generated", "Generated"),
                    ("Completed", "Completed"),
                ],
                default="Temporary",
                max_length=20,
                verbose_name="Completion Status",
            ),
        ),
    ]
